//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zak
    {
        public int id { get; set; }
        public int id_servis { get; set; }
        public string seria { get; set; }
        public decimal prais { get; set; }
    
        public virtual servis servis { get; set; }
    }
}
